apiVersion: gkarthiks.io/v1alpha1
kind: Metrics
metadata:
  name: metrics-ops
spec:
  size: 1
  prometheus:
    image: "prom/prometheus:v2.7.1"
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
