apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metrics-operator
  template:
    metadata:
      labels:
        name: metrics-operator
    spec:
      serviceAccountName: metrics-operator
      containers:
        - name: metrics-operator
          image: gkarthics/metrics-operator:v0.0.1
          command:
          - metrics-operator
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 512Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "metrics-operator"
