// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/gkarthiks/metrics-operator/pkg/apis/gkarthiks/v1alpha1.Metrics":       schema_pkg_apis_gkarthiks_v1alpha1_Metrics(ref),
		"github.com/gkarthiks/metrics-operator/pkg/apis/gkarthiks/v1alpha1.MetricsSpec":   schema_pkg_apis_gkarthiks_v1alpha1_MetricsSpec(ref),
		"github.com/gkarthiks/metrics-operator/pkg/apis/gkarthiks/v1alpha1.MetricsStatus": schema_pkg_apis_gkarthiks_v1alpha1_MetricsStatus(ref),
	}
}

func schema_pkg_apis_gkarthiks_v1alpha1_Metrics(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Metrics is the Schema for the metrics API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/gkarthiks/metrics-operator/pkg/apis/gkarthiks/v1alpha1.MetricsSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/gkarthiks/metrics-operator/pkg/apis/gkarthiks/v1alpha1.MetricsStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/gkarthiks/metrics-operator/pkg/apis/gkarthiks/v1alpha1.MetricsSpec", "github.com/gkarthiks/metrics-operator/pkg/apis/gkarthiks/v1alpha1.MetricsStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_gkarthiks_v1alpha1_MetricsSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MetricsSpec defines the desired state of Metrics",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_gkarthiks_v1alpha1_MetricsStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MetricsStatus defines the observed state of Metrics",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
